services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
  postgrest:
    image: postgrest/postgrest:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_URI: authenticator://admin:password@db:5432/levdev_auth
      DB_SCHEMA: api
      DB_ANON_ROLE: web_anon

      PGRST_DB_URI: postgres://admin:password@db:5432/levdev_auth
      # The:  name of which database schema to expose to REST clients
      PGRST_DB_SCHEMA: api
      # The:  database role to use when no client authentication is provided
      PGRST_DB_ANON_ROLE: web_anon
      # Overrides:  the base URL used within the OpenAPI self-documentation hosted at the API root path
      PGRST_OPENAPI_SERVER_PROXY_URI: http://localhost:3000
    depends_on:
      - db
volumes:
  db_data: