CREATE DATABASE levdev_auth;
\c levdev_auth;

-- Dont need this now but commenting in case i do later
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY generated by default as identity,
    username VARCHAR(25) UNIQUE NOT NULL,
    role_id INTEGER REFERENCES roles(id) ON DELETE SET NULL,
    password TEXT NOT NULL,
    salt TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    token TEXT PRIMARY KEY NOT NULL
);

CREATE INDEX token_hash ON refresh_tokens USING HASH (token);

CREATE TABLE roles (
    id SERIAL PRIMARY KEY,
    name TEXT UNIQUE NOT NULL
);

CREATE TABLE permissions (
    id SERIAL PRIMARY KEY,
    name TEXT UNIQUE NOT NULL
);

CREATE TABLE role_permissions (
    role_id INTEGER REFERENCES roles(id) ON DELETE CASCADE,
    permission_id INTEGER REFERENCES permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

INSERT INTO roles (name) VALUES ('admin'), ('manager'), ('user');

INSERT INTO permissions (name) VALUES ('create'), ('edit'), ('delete');

INSERT INTO role_permissions (role_id, permission_id)
VALUES
    ((SELECT id FROM roles WHERE name = 'admin'), (SELECT id FROM permissions WHERE name = 'create')),
    ((SELECT id FROM roles WHERE name = 'admin'), (SELECT id FROM permissions WHERE name = 'edit')),
    ((SELECT id FROM roles WHERE name = 'admin'), (SELECT id FROM permissions WHERE name = 'delete')),
    ((SELECT id FROM roles WHERE name = 'manager'), (SELECT id FROM permissions WHERE name = 'create')),
    ((SELECT id FROM roles WHERE name = 'manager'), (SELECT id FROM permissions WHERE name = 'edit')),
    ((SELECT id FROM roles WHERE name = 'user'), (SELECT id FROM permissions WHERE name = 'create'));

