CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY generated by default as identity,
    username VARCHAR(25) UNIQUE NOT NULL,
    password TEXT NOT NULL,
    salt TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    token TEXT PRIMARY KEY NOT NULL
);

CREATE INDEX token_hash ON refresh_tokens USING HASH (token);
