CREATE DATABASE levdev_auth;
\c levdev_auth;

-- Dont need this now but commenting in case i do later
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Postgrest initialization
CREATE SCHEMA api;

CREATE TABLE IF NOT EXISTS api.users (
    id int primary key generated by default as identity,
    username VARCHAR(25) NOT NULL,
    password TEXT NOT NULL
);

CREATE ROLE web_anon nologin;

GRANT USAGE ON SCHEMA api to web_anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA api TO web_anon;


CREATE ROLE authenticator noinherit LOGIN PASSWORD 'password';
GRANT web_anon TO authenticator;