spin_manifest_version = 2

[application]
name = "zergerless"
version = "0.1.0"
authors = ["levdev"]
description = "A serverless backend template for zig built on spin"

[[trigger.http]]
route = "/osmo"
component = "codemosis"
executor = { type = "wagi" }

[component.codemosis]
source = "dist/codemosis.wasm"
exclude_files = ["**/node_modules"]
allowed_outbound_hosts = ["https://api.github.com"]
[component.codemosis.build]
command = ["npm install", "npm run build"]
watch = ["src/functions/fetch-active-git-repos.ts"]
